service: 'skluck-hello-world'

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  role: ${env:SERVERLESS_${opt:stage}_ROLE, 'default-lambda-role'}
  environment:
    NODE_ENV: ${opt:stage}

  stage: ${opt:stage}
  region: ${env:SERVERLESS_${opt:stage}_REGION 'us-east-2'}

package:
  individually: true

functions:
  hello:
    handler: 'src/handlers/hello.handler'
    events:
      - http:
          path: users/info
          method: get

  scheduled:
    handler: 'src/handlers/scheduled.handler'
    events:
      - schedule: rate(10 minutes)
